kind: Deployment
apiVersion: apps/v1
metadata:
  name: sphereserver
  namespace: sphereserver
  labels:
    app: sphereserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sphereserver
  template:
    metadata:
      labels:
        app: sphereserver
    spec:
      volumes:
        - name: sphereserver-persistent-storage
          persistentVolumeClaim:
            claimName: uo-sphereserver-data-1
      containers:
        - name: sphereserver
          image: 'naklma/sphereserver:centos-test'
          ports:
            - name: spheresrv2593
              containerPort: 2593
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: sphereserver-persistent-storage
              mountPath: /source/Source/save
              subPath: save
            - name: sphereserver-persistent-storage
              mountPath: /source/Source/accounts
              subPath: accounts
            - name: sphereserver-persistent-storage
              mountPath: /source/Source/logs
              subPath: logs
            - name: sphereserver-persistent-storage
              mountPath: /source/Source/scripts
              subPath: scripts
            - name: sphereserver-persistent-storage
              mountPath: /source/Source/mul
              subPath: mul
            - name: sphereserver-persistent-storage
              mountPath: /source/Source/sphere.ini
              subPath: sphere.ini
            - name: sphereserver-persistent-storage
              mountPath: /source/Source/sphereCrypt.ini
              subPath: sphereCrypt.ini
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          stdin: true
          tty: true
      restartPolicy: Always
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - sphereserver
  revisionHistoryLimit: 1
